# Generated by Django 3.2.3 on 2021-06-03 20:13
import datetime

from django.db import migrations, models
from django.db.models import F


def float_to_minutes_and_seconds(self):
    minutes = int(self.play_time)
    seconds = int((self.play_time - minutes) * 100)
    return minutes, seconds


def fill_play_time(apps, schema_editor):
    Track = apps.get_model('music', 'Track')
    db_alias = schema_editor.connection.alias
    all_tracks = Track.objects.using(db_alias).all()
    for track in all_tracks:
        minutes, seconds = float_to_minutes_and_seconds(track.tmp)
        track.update(play_time=datetime.time(minute=minutes, second=seconds))


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_track_play_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'verbose_name': 'Трек', 'verbose_name_plural': 'Треки'},
        ),
        migrations.AddField(
            model_name='track',
            name='tmp',
            field=models.FloatField()
        ),
        migrations.RunSQL(
            sql=[('UPDATE music_track SET tmp = play_time;')]
        ),
        migrations.AlterField(
            model_name='track',
            name='play_time',
            field=models.TimeField(),
        ),
        migrations.RunPython(fill_play_time),
        migrations.RemoveField(model_name='track', name='tmp')
    ]
